Fix CI for azure/travis
tue-robotics/tue-env pull request #585
Opened 2021-08-04 12:53 UTC by MatthijsBurgh

Get rid of unnecessary spacing in logging.

2021-08-04 19:41 UTC, ar13pit requested changes

2021-08-04 19:41 UTC, ar13pit commented on ci/set-branch.sh
> +DEFAULT_BRANCH=$(curl -H "Accept: application/vnd.github.v3+json" https://api.github.com/repos/"${REPO}" 2>/dev/null | jq ".default_branch" -r)
Why not use the git repo itself to get the default branch? That would free us from using the Github API.

2021-08-05 08:37 UTC, ar13pit requested changes

2021-08-05 08:37 UTC, ar13pit commented on ci/set-branch.sh
> +export BRANCh
Nice typo @MatthijsBurgh :laughing: 
```suggestion
export BRANCH
```

2021-08-05 08:54 UTC, MatthijsBurgh commented on ci/set-branch.sh
> +export BRANCh
Keeping you sharp ;)

2021-08-06 07:44 UTC, ar13pit commented
My only question now is why not use the same logic in GitHub Actions?

2021-08-06 07:53 UTC, MatthijsBurgh commented
> y not use the same logic i

This would require cloning of the repo in single package repo's, which we don't do now. This would require changing the current configs

2021-08-06 08:44 UTC, ar13pit approved these changes

2021-08-06 08:44 UTC, merged