Prepare CI for ROS2
tue-robotics/tue-env pull request #681
Opened 2023-09-04 15:07 UTC by MatthijsBurgh

2023-09-06 19:59 UTC, MatthijsBurgh commented on ci/test-package.sh
> +    docker exec -t tue-env bash -c 'source ~/.bashrc; cd "${TUE_SYSTEM_DIR}" && colcon test --packages-select "${PACKAGE}" --event-handlers desktop_notification- status- terminal_title- console_cohes
Industrial CI runs this with `--executor sequential --ctest-args -j1`, should we do it too?

2023-09-12 19:02 UTC, ar13pit requested changes

2023-09-12 19:02 UTC, ar13pit commented on installer/tue-install-impl.bash
> +    _try_branch_res=$(git -C "${repo}" checkout "${branch}" --recurse-submodules -- 2>&1)  # _try_branch_res is a "global" variable from tue-install-git
Also in `tue-install.bash`

2023-09-12 19:56 UTC, ar13pit approved these changes

2023-09-12 19:58 UTC, merged